### ISSUE TITLE
GO and pathway enrichment analysis

### ISSUE THREAD

**Issue by nfancy** [aertslab/AUCell#13]
Hi,

Thanks for the package. This is more of a query than an issue. I was wondering if it would be appropriate for GO and pathway enrichment analysis similar to GSEA. If yes, what method do you recommend for p-value calculation and multiple testing correction? What is your recommendation in terms of effect size calculation of the enrichment score base on a trait (for example Disease vs Control)? 

Looking forward to hearing from you soon.

Nurun

**Comment by s-aibar** [comment]
Sorry, for questions on how to use the package, see: 
https://github.com/aertslab/AUCell/issues/26
