### ISSUE TITLE
Condition comparison in AUCell

### ISSUE THREAD

**Issue by kmshort** [aertslab/AUCell#19]
Hi all,
Can we do condition testing (treated vs untreated) using AUCell?
i.e. if I start a SCENIC project with a seurat object with metadata for different conditions in seurat$conds, can I just test Treatment1 vs Treatment2 using seurat$conds metadata?
I ask, because, from my reading of the "Limitations" section in [Van de Sande et. al. (2020), Nat. Prot.](https://www.nature.com/articles/s41596-020-0336-2), it appears you can't because, from the paper " the scores of different regulons cannot be compared". But is my interpretation of that wrong? 
thanks,
Kieran

**Comment by s-aibar** [comment]
Sorry, for questions on how to use the package, see: 
https://github.com/aertslab/AUCell/issues/26
