### ISSUE TITLE
All zeros for regulon's AUC

### ISSUE THREAD

**Issue by topherconley** [aertslab/AUCell#2]
Hi, 

I ran pySCENIC's workflow to generate AUC values followed by `AUC_exploreThresholds` from the latest version (1.2.4) of `AUCell`.

```
cells_assignment <- AUCell_exploreThresholds(auc,plotHist=F, assign=TRUE, nCores = 30, verbose = T) 
```

which results in this error.

> Error in { : task 386 failed - "missing value where TRUE/FALSE needed"

It turns out that the **regulon with index 386 had all zeros for the AUC.**

I recommend removing this regulons from consideration or at least issue a warning so other users don't get tripped up on this.  By the way, is it possible that some assumption is being violated in the calculation of AUC when you notice a regulon has an AUC of all zeros? 

All the best,
Chris

**Comment by s-aibar** [comment]
Thank you,
This is now solved in newer versions of the packages.
