### ISSUE TITLE
AUCell ranking test

### ISSUE THREAD

**Issue by chansigit** [aertslab/AUCell#20]
Dear developers,

have you tested that snippet thoroughly yet? if you have thoroughly tested it, i suggest removing that little annotation, which really makes us nervous.

`https://github.com/aertslab/AUCell/blob/7430c16edcc6a5b20fa068f16b259ad86d0ba874/R/01_buildRankings.R#L112`

:D

**Comment by s-aibar** [comment]
Done, thanks! :)
