### ISSUE TITLE
thresholds for comparibility from one dataset to another ?

### ISSUE THREAD

**Issue by Lan-h** [aertslab/AUCell#22]
Hi ! 
I would like to use AUCell on different datasets with different sequencing depth.
Some of them are already integrated so I guess  another issue is that 0 have also been added in the count matrices.

I wonder if there is a way to take this into account and set different thresholds to offset the different sequencing depth and be able to compare AUC scores across datasets. 

Thanks in advance for your help !

**Comment by Lan-h** [comment]
NB: I tried to "normalize" the thresholds based on sequencing depth so as to get a constant top number of genes, but it is not working on all datasets so I wondered if there was another parameter to be taken into account to be able to compare datasets.

**Comment by s-aibar** [comment]
Sorry, for questions on how to use the package, see: 
https://github.com/aertslab/AUCell/issues/26
