### ISSUE TITLE
Run AUCell_buildRankings on HVG?

### ISSUE THREAD

**Issue by aelhossiny** [aertslab/AUCell#24]
Hi, thank you for such a wonderful tool,

I've an integrated dataset of ~121k cells with ~50k features, running `AUCell_buildRankings()` on this dataset keeps giving me that error

```
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
```
 
I understand that this is a memory issue, can I run it on the top 2000 HVG as it's routinely done in other analyses? Or is it better to run it on individual samples separatly on whole genes?

**Comment by s-aibar** [comment]
Sorry, for questions on how to use the package, see: 
https://github.com/aertslab/AUCell/issues/26
