### ISSUE TITLE
Clustering enrichment results

### ISSUE THREAD

**Issue by Dillon214** [aertslab/AUCell#31]
Hello AUCell team,

Im a junior bioinformatician and have recently found/used AUCell in a project I'm working on. Becuase the enrichments are single-cell resolved, I was wondering if it would be possible to cluster the cells I have in enrichment space. The bio team I support is very interested in this. 
Do you have any tips for how to cluster the AUCell enrichment data in a UMAP?

**Comment by s-aibar** [comment]
Sorry, for questions on how to use the package, see: 
https://github.com/aertslab/AUCell/issues/26
