### ISSUE TITLE
Determining 'active' pathways en masse

### ISSUE THREAD

**Issue by Dillon214** [aertslab/AUCell#32]
Hello AUCell creator(s),

I am interested in using AUCell to determine the functional retinues of various clusters in an analysis I'm pursuing. However, one issue I've ran into is filtering results, and furthermore, determining how what differences in enrichment are 'significant'. I think there is a bias toward small gene sets in enrichment calculation, making it so small gene sets have inflated differences in enrichment score. Is there a way to computationally determine which pathways are uniquely enriched for a function? Any help would be appreciated.

**Comment by s-aibar** [comment]
Sorry, for questions on how to use the package, see: 
https://github.com/aertslab/AUCell/issues/26
