### ISSUE TITLE
Recommended for use on Aggregated data? 

### ISSUE THREAD

**Issue by daacarri** [aertslab/AUCell#4]
Hello, 

I'm trying to find cells with a hypoxic signature, but am using aggregated data from two different experimental conditions. 

I am getting very low numbers, and was wondering if it isn't because I'm using the aggregated data. Would it be better to identify cells from each of the individual data sets? 

Any help would be appreciated.

**Comment by s-aibar** [comment]
Hello,

I'm not sure what do you mean with "aggregated data" (do you mean concatenated datasets?). In principle, it is fine to just `cbind` the expression matrices or rankings if they come from similar datasets (e.g. so if there is similar coverage; the ranking is calculated individually for each cell).

However, to understand what is going on you might need to check it a bit further (maybe you need to adjust the `aucMaxRank`?).
