### ISSUE TITLE
determining thresholds

### ISSUE THREAD

**Issue by ceesu** [aertslab/AUCell#8]
Hello, thank you very much for your development of this package. 
I noticed that the signature thresholds that are automatically found for my single cell data are not always a great fit in the distributions of frequency vs. AUC. Do you think that it may be help for the input expression matrix to be normalized? If so how might this affect the auc scores and the final cell assignments?

**Comment by s-aibar** [comment]
The normalization of the input matrices should not affect much. The AUC is calculated for each cell individually. 
We have not found a better way to automate the thresholds, though. So they still need some user supervision...
